/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Buku.java
 *
 * Created on Mar 27, 2014, 1:49:48 PM
 */

package perpustakaan_form;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfigurasi.tengah;
import javax.swing.*;

/**
 *
 * @author YANET
 */
public class Buku extends javax.swing.JFrame {
Connection koneksi=null;
DefaultTableModel TabModel;
ResultSet buku=null;
    /** Creates new form Buku */
    public Buku() {
        initComponents();
        tampildata();     
        icon();
    }
    
    void icon(){
        ImageIcon ico= new ImageIcon("src/icon/book.png");
        setIconImage(ico.getImage());
    }
    
    void tampildata(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
           System.out.println("Berhasil Load Driver");
        }  catch(ClassNotFoundException cnfe){
           System.out.println("Tidak ada Driver "+cnfe);
           }
        try{
           koneksi=DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan","root","");
           System.out.println("Berhasil Koneksi Database");
        }  catch(SQLException se){
           System.out.println("Gagal Koneksi "+se);
           JOptionPane.showMessageDialog(null,"Gagal Koneksi Database","Peringatan",JOptionPane.WARNING_MESSAGE);
           }
           
        try{
            Object[] judul_kolom={"Id Buku", "Judul", "Penerbit", "Tahun Terbit"};
            TabModel=new DefaultTableModel(null,judul_kolom);
            jTable1.setModel(TabModel);
            Statement stm;
            stm=koneksi.createStatement();
            TabModel.getDataVector().removeAllElements();
            buku=stm.executeQuery("select * from buku");
            while (buku.next()){
                Object[] data={buku.getString("id_buku"),
                               buku.getString("judul_buku"),
                               buku.getString("penerbit"),
                               buku.getString("tahun_terbit") 
                              };
                TabModel.addRow(data);
                }
         }  catch(Exception e){
            e.printStackTrace();
            }
    }
    
    void hapusfield(){
        TextFieldKodeBuku.setText("");
        TextFieldJudulBuku.setText("");
        TextFieldPenerbit.setText("");
        TextFieldTahunTerbit.setText("");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldTahunTerbit = new javax.swing.JTextField();
        TextFieldPenerbit = new javax.swing.JTextField();
        TextFieldKodeBuku = new javax.swing.JTextField();
        TextFieldJudulBuku = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buku Perpustakaan");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(-16711681,true));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABEL BUKU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 417, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Kode Buku ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Judul Buku ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Penerbit    ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 17));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Thn Terbit ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jPanel1.add(TextFieldTahunTerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 168, -1));
        jPanel1.add(TextFieldPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 168, -1));
        jPanel1.add(TextFieldKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 168, -1));
        jPanel1.add(TextFieldJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 168, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jButton4.setText("  Hapus");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 110, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/disk.png"))); // NOI18N
        jButton1.setText("  Simpan");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 110, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/email_edit.png"))); // NOI18N
        jButton2.setText("  Edit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 110, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.gif"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 110, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.gif"))); // NOI18N
        jButton6.setText("Menu Utama");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 306, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul", "Penerbit", "Tahun Terbit"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 194, 384, 101));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        dispose();
        new menu_utama().setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        hapusfield();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       try{
    Statement stm=koneksi.createStatement();
    stm.executeUpdate("insert into buku set id_buku='"+TextFieldKodeBuku.getText()+"',"+
                      "judul_buku='"+TextFieldJudulBuku.getText()+"',"+
                      "penerbit='"+TextFieldPenerbit.getText()+"',"+
                      "tahun_terbit='"+TextFieldTahunTerbit.getText()+"'");
         hapusfield();
         tampildata();
         TextFieldKodeBuku.requestFocus();
       } catch(Exception e){
         e.printStackTrace();
         }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    TextFieldKodeBuku.setText(TabModel.getValueAt(jTable1.getSelectedRow(),0)+"");
    TextFieldJudulBuku.setText(TabModel.getValueAt(jTable1.getSelectedRow(),1)+"");
    TextFieldPenerbit.setText(TabModel.getValueAt(jTable1.getSelectedRow(),2)+"");
    TextFieldTahunTerbit.setText(TabModel.getValueAt(jTable1.getSelectedRow(),3)+"");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      try{
    Statement stm=koneksi.createStatement();
    stm.executeUpdate("delete from buku where id_buku='"+
            TabModel.getValueAt(jTable1.getSelectedRow(),0)+"'");
    tampildata();
    hapusfield();
    }catch(Exception e){
    e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     try{
    Statement stm=koneksi.createStatement();
    stm.executeUpdate("update buku set id_buku='"+TextFieldKodeBuku.getText()+"',"+
                       "judul_buku='"+TextFieldJudulBuku.getText()+"',"+
                       "penerbit='"+TextFieldPenerbit.getText()+"',"+
                       "tahun_terbit='"+TextFieldTahunTerbit.getText()+"'where id_buku='"+
                       TabModel.getValueAt(jTable1.getSelectedRow(),0)+"'");
    tampildata();
    hapusfield();
    }catch(Exception e){
    e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        new tengah(this);
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldJudulBuku;
    private javax.swing.JTextField TextFieldKodeBuku;
    private javax.swing.JTextField TextFieldPenerbit;
    private javax.swing.JTextField TextFieldTahunTerbit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
